Revert "[BOARDCONFIG] TWRP: Build TWRP together with ROM by default"
Fixes build failure:
vendor/cm/charger/healthd_board_cm.cpp:86: error: undefined reference to 'gr_sys_font()'
vendor/cm/charger/healthd_board_cm.cpp:86: error: undefined reference to 'gr_font_size(GRFont const*, int*, int*)'
vendor/cm/charger/healthd_board_cm.cpp:87: error: undefined reference to 'gr_sys_font()'
vendor/cm/charger/healthd_board_cm.cpp:87: error: undefined reference to 'gr_measure(GRFont const*, char const*)'
vendor/cm/charger/healthd_board_cm.cpp:93: error: undefined reference to 'gr_sys_font()'
vendor/cm/charger/healthd_board_cm.cpp:93: error: undefined reference to 'gr_text(GRFont const*, int, int, char const*, bool)'
system/core/healthd/healthd_mode_charger.cpp:591: error: undefined reference to 'gr_sys_font()'
system/core/healthd/healthd_mode_charger.cpp:591: error: undefined reference to 'gr_font_size(GRFont const*, int*, int*)'
system/core/healthd/healthd_mode_charger.cpp:558: error: undefined reference to 'gr_init_font(char const*, GRFont**)'
system/core/healthd/healthd_mode_charger.cpp:565: error: undefined reference to 'gr_init_font(char const*, GRFont**)'
system/core/healthd/healthd_mode_charger.cpp:453: error: undefined reference to 'gr_text(GRFont const*, int, int, char const*, bool)'
system/core/healthd/healthd_mode_charger.cpp:477: error: undefined reference to 'gr_text(GRFont const*, int, int, char const*, bool)'
system/core/healthd/healthd_mode_charger.cpp:388: error: undefined reference to 'gr_measure(GRFont const*, char const*)'
system/core/healthd/healthd_mode_charger.cpp:394: error: undefined reference to 'gr_text(GRFont const*, int, int, char const*, bool)'

This reverts commit 3705336a4e91440b77c947720058c87c589d4d0f.