[BOARDCONFIG] TWRP: Disable TARGET_HW_DISK_ENCRYPTION
D10F doesn't support it yet.

Also, this cause TWRP build failure:
bootable/recovery-twrp/crypto/lollipop/cryptfs.c:114: error: undefined reference to 'should_use_keymaster'